component_management:
  individual_components:
    - component_id: engine  # this is an identifier that should not be changed
      name: engine  # this is a display name, and can be changed freely
      paths: app/src/main/java/com/io/minesweeper/game_engine
