name: Android Lint and Test

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
      
      - name: Run Lint
        run: ./gradlew lint

      - name: Upload Lint Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: '**/build/reports/lint-results-*'